# Basic Information 
title: Yiwei Wang
position: Postdoc
affiliation: UCLA
affiliation_link: https://web.cs.ucla.edu/~kwchang/members/
email: wangyw.evan@gmail.com

# Search Engine Optimization (SEO)
keywords: yiwei wang, wang yiwei, nus, ucla, amazon, natural language processing, graph neural networks
canonical: https://wangywust.github.io/
description: Yiwei Wang is a Postdoc at UCLA. His research lies in natural language processing and graph neural networks.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com.hk/citations?user=Sh9QvBkAAAAJ&hl=en
cv_link: Yiwei_CV.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/yiwei-wang-b632a5118/
twitter: https://twitter.com/wangyiw33973985

# Images 
avatar: ./photo.jpg
favicon: ./assets/img/450.png
favicon_dark: ./assets/img/450.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
